-- MySQL Script generated by MySQL Workbench
-- Fri Sep 20 08:37:02 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`biblioteca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`biblioteca` ;

CREATE TABLE IF NOT EXISTS `mydb`.`biblioteca` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cadastro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cadastro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cadastro` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `biblioteca_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cadastro_biblioteca_idx` (`biblioteca_id` ASC) VISIBLE,
  CONSTRAINT `fk_cadastro_biblioteca`
    FOREIGN KEY (`biblioteca_id`)
    REFERENCES `mydb`.`biblioteca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`endereco_cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`endereco_cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`endereco_cliente` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cep` DECIMAL(9) NOT NULL,
  `numero` DECIMAL(4) NOT NULL,
  `tipo` VARCHAR(20) NOT NULL,
  `complemento` TEXT(100) NULL,
  `comprovante_endereco` BLOB NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cliente_usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cliente_usuario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(50) NOT NULL,
  `nome_completo` VARCHAR(50) NOT NULL,
  `data_nasc` DATE NOT NULL,
  `documentos` DECIMAL(12) NOT NULL,
  `cadastro_id` INT UNSIGNED NOT NULL,
  `endereco_cliente_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cliente_usuario_cadastro1_idx` (`cadastro_id` ASC) VISIBLE,
  INDEX `fk_cliente_usuario_endereco_cliente1_idx` (`endereco_cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_usuario_cadastro1`
    FOREIGN KEY (`cadastro_id`)
    REFERENCES `mydb`.`cadastro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_usuario_endereco_cliente1`
    FOREIGN KEY (`endereco_cliente_id`)
    REFERENCES `mydb`.`endereco_cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`atendente_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`atendente_usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`atendente_usuario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(50) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `data_nasc` DATE NULL,
  `documentos` DECIMAL(12) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estante` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estante` (
  `id` INT UNSIGNED NOT NULL,
  `cliente_usuario_id` INT UNSIGNED NOT NULL,
  `qnt_livros` DECIMAL(1) NOT NULL,
  `genero_mais` VARCHAR(100) NOT NULL,
  `tipo_livro` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estante_cliente_usuario1_idx` (`cliente_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_estante_cliente_usuario1`
    FOREIGN KEY (`cliente_usuario_id`)
    REFERENCES `mydb`.`cliente_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`livro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`livro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`livro` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numero_pags` DECIMAL(4) NOT NULL,
  `idioma` VARCHAR(20) NOT NULL,
  `data_publicacao` DATE NOT NULL,
  `isbn-10` DECIMAL(10) NOT NULL,
  `isbn-13` DECIMAL(14) NOT NULL,
  `titulo` VARCHAR(50) NOT NULL,
  `autor` VARCHAR(50) NOT NULL,
  `classificacao` VARCHAR(45) NOT NULL,
  `situacao` VARCHAR(45) NOT NULL,
  `biblioteca_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_livro_biblioteca1_idx` (`biblioteca_id` ASC) VISIBLE,
  CONSTRAINT `fk_livro_biblioteca1`
    FOREIGN KEY (`biblioteca_id`)
    REFERENCES `mydb`.`biblioteca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genero_lit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`genero_lit` ;

CREATE TABLE IF NOT EXISTS `mydb`.`genero_lit` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `biblioteca_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_genero_lit_biblioteca1_idx` (`biblioteca_id` ASC) VISIBLE,
  CONSTRAINT `fk_genero_lit_biblioteca1`
    FOREIGN KEY (`biblioteca_id`)
    REFERENCES `mydb`.`biblioteca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`emprétimos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`emprétimos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`emprétimos` (
  `id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`multa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`multa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`multa` (
  `id` INT UNSIGNED NOT NULL,
  `prazo` DECIMAL(2) NULL,
  `emprétimos_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_multa_emprétimos1_idx` (`emprétimos_id` ASC) VISIBLE,
  CONSTRAINT `fk_multa_emprétimos1`
    FOREIGN KEY (`emprétimos_id`)
    REFERENCES `mydb`.`emprétimos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`posse_livro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`posse_livro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`posse_livro` (
  `id` INT UNSIGNED NOT NULL,
  `qnt_livros` DECIMAL(1) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `emprétimos_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_posse_livro_emprétimos1_idx` (`emprétimos_id` ASC) VISIBLE,
  CONSTRAINT `fk_posse_livro_emprétimos1`
    FOREIGN KEY (`emprétimos_id`)
    REFERENCES `mydb`.`emprétimos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`doacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`doacao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`doacao` (
  `id` INT UNSIGNED NOT NULL,
  `qnt_livros` DECIMAL(2) NULL,
  `livro_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_doacao_livro1_idx` (`livro_id` ASC) VISIBLE,
  CONSTRAINT `fk_doacao_livro1`
    FOREIGN KEY (`livro_id`)
    REFERENCES `mydb`.`livro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estante` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estante` (
  `id` INT UNSIGNED NOT NULL,
  `cliente_usuario_id` INT UNSIGNED NOT NULL,
  `qnt_livros` DECIMAL(1) NOT NULL,
  `genero_mais` VARCHAR(100) NOT NULL,
  `tipo_livro` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estante_cliente_usuario1_idx` (`cliente_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_estante_cliente_usuario1`
    FOREIGN KEY (`cliente_usuario_id`)
    REFERENCES `mydb`.`cliente_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`preferencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`preferencias` ;

CREATE TABLE IF NOT EXISTS `mydb`.`preferencias` (
  `id` INT UNSIGNED NOT NULL,
  `genero` VARCHAR(100) NOT NULL,
  `livro` VARCHAR(45) NOT NULL,
  `recomendacoes_genero` VARCHAR(45) NOT NULL,
  `recomendacoes_livros` VARCHAR(45) NOT NULL,
  `tipoliv_de_preferencia` VARCHAR(45) NOT NULL,
  `cliente_usuario_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_preferencias_cliente_usuario1_idx` (`cliente_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_preferencias_cliente_usuario1`
    FOREIGN KEY (`cliente_usuario_id`)
    REFERENCES `mydb`.`cliente_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`acervo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`acervo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`acervo` (
  `id` INT UNSIGNED NOT NULL,
  `comentarios_livro` TEXT(280) NOT NULL,
  `nota_leitores` DECIMAL(1) NOT NULL,
  `acervocol` VARCHAR(45) NULL,
  `livro_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_acervo_livro1_idx` (`livro_id` ASC) VISIBLE,
  CONSTRAINT `fk_acervo_livro1`
    FOREIGN KEY (`livro_id`)
    REFERENCES `mydb`.`livro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
