-- MySQL Script generated by MySQL Workbench
-- Wed Sep  4 09:24:32 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bibliotecabd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bibliotecabd` ;

-- -----------------------------------------------------
-- Schema bibliotecabd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bibliotecabd` DEFAULT CHARACTER SET utf8 ;
USE `bibliotecabd` ;

-- -----------------------------------------------------
-- Table `bibliotecabd`.`Autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bibliotecabd`.`Autor` ;

CREATE TABLE IF NOT EXISTS `bibliotecabd`.`Autor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `nacionalidade` VARCHAR(45) NULL,
  `nascimento` DATE NULL,
  `bio` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecabd`.`Livro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bibliotecabd`.`Livro` ;

CREATE TABLE IF NOT EXISTS `bibliotecabd`.`Livro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `isbn` VARCHAR(13) NULL,
  `publicacao` YEAR NULL,
  `editora` VARCHAR(50) NULL,
  `genero` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecabd`.`AutorEscreveLivro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bibliotecabd`.`AutorEscreveLivro` ;

CREATE TABLE IF NOT EXISTS `bibliotecabd`.`AutorEscreveLivro` (
  `autorId` INT NOT NULL,
  `livroId` INT NOT NULL,
  PRIMARY KEY (`autorId`, `livroId`),
  INDEX `fk_Autor_has_Livro_Livro1_idx` (`livroId` ASC) VISIBLE,
  INDEX `fk_Autor_has_Livro_Autor_idx` (`autorId` ASC) VISIBLE,
  CONSTRAINT `fk_Autor_has_Livro_Autor`
    FOREIGN KEY (`autorId`)
    REFERENCES `bibliotecabd`.`Autor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Autor_has_Livro_Livro1`
    FOREIGN KEY (`livroId`)
    REFERENCES `bibliotecabd`.`Livro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecabd`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bibliotecabd`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `bibliotecabd`.`Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `usuario` VARCHAR(45) NULL,
  `senha` VARCHAR(80) NULL,
  `email` VARCHAR(255) NULL,
  `telefone` VARCHAR(20) NULL,
  `endereco` VARCHAR(100) NULL,
  `tipo` ENUM('Aluno', 'Professor') NULL,
  `cadastro` TIMESTAMP(3) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecabd`.`Emprestimo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bibliotecabd`.`Emprestimo` ;

CREATE TABLE IF NOT EXISTS `bibliotecabd`.`Emprestimo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `emprestimo` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `devolucao` DATE NULL,
  `usuarioId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Emprestimo_Usuario1_idx` (`usuarioId` ASC) VISIBLE,
  CONSTRAINT `fk_Emprestimo_Usuario1`
    FOREIGN KEY (`usuarioId`)
    REFERENCES `bibliotecabd`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecabd`.`Exemplar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bibliotecabd`.`Exemplar` ;

CREATE TABLE IF NOT EXISTS `bibliotecabd`.`Exemplar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NULL,
  `observacao` TEXT NULL,
  `livroId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Exemplar_Livro1_idx` (`livroId` ASC) VISIBLE,
  CONSTRAINT `fk_Exemplar_Livro1`
    FOREIGN KEY (`livroId`)
    REFERENCES `bibliotecabd`.`Livro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecabd`.`EmprestimoPossuiExemplar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bibliotecabd`.`EmprestimoPossuiExemplar` ;

CREATE TABLE IF NOT EXISTS `bibliotecabd`.`EmprestimoPossuiExemplar` (
  `emprestimoId` INT NOT NULL,
  `exemplarId` INT NOT NULL,
  PRIMARY KEY (`emprestimoId`, `exemplarId`),
  INDEX `fk_Emprestimo_has_Exemplar_Exemplar1_idx` (`exemplarId` ASC) VISIBLE,
  INDEX `fk_Emprestimo_has_Exemplar_Emprestimo1_idx` (`emprestimoId` ASC) VISIBLE,
  CONSTRAINT `fk_Emprestimo_has_Exemplar_Emprestimo1`
    FOREIGN KEY (`emprestimoId`)
    REFERENCES `bibliotecabd`.`Emprestimo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Emprestimo_has_Exemplar_Exemplar1`
    FOREIGN KEY (`exemplarId`)
    REFERENCES `bibliotecabd`.`Exemplar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
